name: dive_prep
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  background_downloader: ^8.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  intl: ^0.19.0 # For formatting file sizes
  shared_preferences: ^2.2.2
  open_file_plus: ^3.3.0 # To open the video file
  url_launcher: ^6.2.5   # Helper for some path actions
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5 # Optional, but helps with state comparison

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.3

icons_launcher:
  image_path: "static/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    linux:
      enable: true
    windows: 
      enable: true
    macos: 
      enable: true

flutter:
  uses-material-design: true
